/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.first.application

import io.javalin.Javalin

class App {
    val greeting: String
        get() {
            return "Hello"
        }
}

fun main(args: Array<String>) {
    val app = Javalin.create().start(7000)
    app.get("/") { ctx->ctx.result(App().greeting) }
    app.get("/wel") { ctx->ctx.result("Welcome to the first program in javalin") }
}
    